---
- name: "{{ zookeeper_task_prefix }} Create group"
  ansible.builtin.group:
    name: "{{ zookeeper_group }}"
    state: present

- name: "{{ zookeeper_task_prefix }} Create user"
  ansible.builtin.user:
    name: "{{ zookeeper_user }}"
    shell: "{{ zookeeper_user_shell }}"
    group: "{{ zookeeper_group }}"
    state: present

- name: "{{ zookeeper_task_prefix }} Download tarball"
  ansible.builtin.get_url:
    url: "{{ zookeeper_download_url_file }}"
    dest: "{{ zookeeper_path_tarball }}"
    checksum: "{{ zookeeper_download_checksum }}"

- name: "{{ zookeeper_task_prefix }} Unpack tarball"
  ansible.builtin.unarchive:
    src: "{{ zookeeper_path_tarball }}"
    dest: "{{ zookeeper_path_base }}"
    remote_src: true

- name: "{{ zookeeper_task_prefix }} Copy binaries"
  ansible.builtin.copy:
    src: "{{ zookeeper_path_unpacked }}"
    dest: "{{ zookeeper_path_install }}"
    remote_src: true

- name: "{{ zookeeper_task_prefix }} Create data and log directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: '0755'
  loop:
    - "{{ zookeeper_path_data }}"
    - "{{ zookeeper_path_log }}"

- name: "{{ zookeeper_task_prefix }} Put config file"
  ansible.builtin.template:
    src: "{{ zookeeper_template_config }}"
    dest: "{{ zookeeper_path_config }}/zoo.cfg"

- name: "{{ zookeeper_task_prefix }} Put id file"
  ansible.builtin.copy:
    content: "{{ zk_id }}"
    dest: "{{ zookeeper_path_data }}/myid"
    owner: root
    group: root
    mode: '0644'

- name: "{{ zookeeper_task_prefix }} Put service file"
  ansible.builtin.template:
    src: "{{ zookeeper_template_systemd }}"
    dest: "{{ zookeeper_path_systemd }}"
    owner: root
    group: root
    mode: '0644'

- name: "{{ zookeeper_task_prefix }} Apply systemd unit"
  ansible.builtin.systemd:
    name: "{{ zookeeper_systemd_name }}"
    enabled: "{{ zookeeper_systemd_enabled }}"
    masked: "{{ zookeeper_systemd_masked }}"
    state: "{{ zookeeper_systemd_state }}"
    daemon_reload: "{{ zookeeper_systemd_daemon_reload }}"
...
